### ISSUE TITLE
installation instructions, release, pip package

### ISSUE THREAD

**Issue by AntonioJBT** [saphir746/BiobankRead-Bash#10]
Hello!
Looks great, you may want to provide instructions for installation, make it pip install-able and add a release in GitHub?
It already has a setup.py so might be that the instructions are incomplete at the moment?
Best,
Antonio

**Comment by AntonioJBT** [comment]
Further to the above:
re comes by default with python so no need to specify it as an additional dependence (I forgot so tried conda then pip and couldn't find it).
You could maybe add eg:
```
conda create -n biobankread
conda activate biobankread
conda install -y python pandas beautifulSoup4 urllib3 seaborn
pip install biobankread
```
to the instructions. 

Also, just noticed your setup.py is empty. I have a more involved [template](https://github.com/AntonioJBT/project_quickstart/blob/master/templates/project_template/setup.py) which is useful if you want to install scripts that run from the command line.
Would you be happy accepting pull requests? I could try adding some of these files if helpful.
Best,
Antonio

**Comment by saphir746** [comment]
Added - conda usage example to README.txt

**Comment by saphir746** [comment]
* .rst not .txt

**Comment by AntonioJBT** [comment]
👍
